/**
 * Regression guard for issue #526.
 *
 * The gallery's component DETAIL pages (`website/app/ui/[name]/page.ts`)
 * statically import the component SOURCES from `components/ui/*.ts`. Those
 * files do not exist in a fresh tree: they are a gitignored mirror of
 * `packages/ui/packages/registry/`, generated by `scripts/copy-registry.mjs`.
 *
 * The deploy image serves each app with a direct `bun .../webjs.js start`, which
 * BYPASSES npm `prestart`. So the generated `components/ui/` sources have to be
 * baked into the image at BUILD time (exactly like the Tailwind css is), or every
 * component page 500s in production with `Cannot find module
 * '#components/ui/<name>.ts'`. That is what happened on the Bun cutover (#522):
 * the home pages worked, the component pages did not, and a home-route-only
 * smoke missed it.
 *
 * The gallery moved from the old ui host to the marketing site in #1099, so the
 * bake moved with it; the failure mode it guards against is unchanged.
 *
 * This asserts the Dockerfile bakes the registry copy at build time, so removing
 * that step (or never adding it) fails CI here instead of only at deploy time.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const dockerfile = readFileSync(join(ROOT, 'Dockerfile'), 'utf8');

test('the Dockerfile bakes the ui registry components at build time (#526)', () => {
  // A RUN step must invoke the registry-copy script. Match the script name
  // rather than an exact command so a future `cd`/path tweak does not falsely
  // fail, while a dropped bake step (the actual regression) does.
  const runsCopyRegistry = /^RUN\b.*copy-registry\.mjs/m.test(dockerfile);
  assert.ok(
    runsCopyRegistry,
    'Dockerfile must RUN scripts/copy-registry.mjs so components/ui/*.ts ship in the image; ' +
      'without it the /ui component pages 500 when served directly on Bun (bypassing npm prestart, #526).',
  );
});

test('the registry-copy script the bake depends on still exists', () => {
  // If the script moves/renames, the Dockerfile RUN above silently no-ops at
  // build (a missing script is a hard `docker build` error, but this catches a
  // rename in the repo before the image build does).
  const script = join(ROOT, 'website', 'scripts', 'copy-registry.mjs');
  assert.ok(existsSync(script), `copy-registry.mjs must exist at ${script} for the Dockerfile bake to work`);
});

test('the registry copy runs BEFORE the Tailwind build', () => {
  // Ordering is load-bearing and nothing else catches it. The generated
  // sources are a scanned `@source` in website/public/input.css, so a
  // stylesheet compiled before they exist is missing every utility class the
  // kit's components use: the previews render structurally correct and
  // completely unstyled, in production only.
  const copyAt = dockerfile.search(/^RUN\b.*copy-registry\.mjs/m);
  const tailwindAt = dockerfile.search(/^RUN\b.*tailwindcss/m);
  assert.ok(copyAt >= 0 && tailwindAt >= 0, 'both build steps are present');
  assert.ok(
    copyAt < tailwindAt,
    'copy-registry.mjs must run before the Tailwind build, or the kit utility classes are missing from the compiled stylesheet',
  );
});
